services:
  server:
    image: engingokmen/alarm-backend:1.0.0
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://database:27017/
    ports:
      - 9000:9000
  database:
    image: mongo
    restart: always
