services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    image: engingokmen/alarm-backend:1.0.1
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://database:27017/
    labels:
      - "traefik.http.routers.server.rule=Host(`server.docker.localhost`)"
  database:
    image: mongo
    restart: always
