services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
      --entryPoints.websecure.address=:443
      --certificatesresolvers.myresolver.acme.tlschallenge=true
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
  server:
    image: engingokmen/alarm-backend:1.0.2
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://database:27017/
    labels:
      - traefik.http.routers.server.rule=Host(`price-alarm.engingokmen.com`)
      - traefik.http.routers.server.entrypoints=websecure
      - traefik.http.routers.server.tls.certresolver=myresolver
  database:
    image: mongo
    restart: always
