services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
  server:
    image: engingokmen/alarm-backend:1.0.0
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://database:27017/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`price-alarm.engingokmen.com`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"
  database:
    image: mongo
    restart: always
